# Generated by Django 4.0.2 on 2022-03-01 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player_mode', models.CharField(choices=[('READY_TO_PLAY', 'Ready to Play'), ('PLAYING', 'Playing'), ('OFFLINE', 'Offline'), ('Online', 'Online')], max_length=20)),
                ('player_level', models.CharField(choices=[('NOVICE', 'Novice'), ('BEGINEERS', 'Begineers'), ('INTERMEDIATS', 'Intermediats'), ('EXPERT', 'Expert')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
